### ISSUE TITLE
Pins on breadboard

### ISSUE THREAD

**Issue by kfrancis** [newdigate/teensy-3.6#1]
Is it possible to have it hook on the breadboard view directly rather than require wires?

**Comment by newdigate** [comment]
Yes, I noticed that the pins don't automatically connect when dropping the teensy onto the breadboard. I am fairly new to Fritzing and assumed this was default behaviour; It would be much better if the connections automatically wired correctly when dropping into the breadboard; I will have to look into this...

**Comment by newdigate** [comment]
I think it is because the pins are not "male" pins. I might be inspired to fix this if this repository gets a star.

**Comment by newdigate** [comment]
The pins are marked as male now, they auto-connect to the breadboard pins.
